import { uniqueTokens } from './segments';
import type { Project, Question, Segment, TokenSegment } from '@/types';

export const MARK_OPEN = '‹';
export const MARK_CLOSE = '›';
export const MARK_LEGEND = `${MARK_OPEN}Marked like this${MARK_CLOSE} = generated by Recall and not yet verified by the candidate.`;

/** Unverified spans stay marked in every export. There is no setting for this. */
export function segmentsToExportText(segments: Segment[]): string {
  return segments
    .map((s) =>
      s.kind === 'token' && s.state === 'unverified'
        ? `${MARK_OPEN}${s.text}${MARK_CLOSE}`
        : s.text,
    )
    .join('');
}

export interface Correction {
  questionText: string;
  original: string;
  current: string;
  note?: string;
}

export function corrections(project: Project): Correction[] {
  const out: Correction[] = [];
  for (const question of project.questions) {
    for (const token of uniqueTokens(question.shortAnswer, question.longAnswer)) {
      if (token.state !== 'edited') continue;
      out.push({
        questionText: question.text,
        original: token.originalText,
        current: token.text,
        note: token.userNote,
      });
    }
  }
  return out;
}

export interface ExportStats {
  total: number;
  resolved: number;
  unverified: TokenSegment[];
}

export function exportStats(project: Project): ExportStats {
  const unverified: TokenSegment[] = [];
  let total = 0;
  let resolved = 0;
  for (const question of project.questions) {
    for (const token of uniqueTokens(question.shortAnswer, question.longAnswer)) {
      total++;
      if (token.state === 'unverified') unverified.push(token);
      else resolved++;
    }
  }
  return { total, resolved, unverified };
}

export function verificationFooter(project: Project): string {
  const { total, resolved, unverified } = exportStats(project);
  const date = new Date().toLocaleString();
  if (total === 0) {
    return `Prepared with Recall on ${date}. This document contains no generated specifics.`;
  }
  return unverified.length === 0
    ? `Prepared with Recall on ${date}. All ${total} generated specifics were confirmed or corrected by the candidate.`
    : `Prepared with Recall on ${date}. ${resolved} of ${total} generated specifics were confirmed or corrected by the candidate; ${unverified.length} remain unverified and are marked in the text.`;
}

function roleLabel(project: Project, question: Question): string {
  const role = project.resume.roles.find((r) => r.id === question.sourceRoleId);
  return role ? `${role.title}, ${role.employer}` : 'No source role';
}

export function buildMarkdown(project: Project): string {
  const stats = exportStats(project);
  const lines: string[] = [];

  lines.push(`# ${project.name}`, '');

  // Fast mode carries the unverified list at the top of the document.
  if (project.mode === 'fast' && stats.unverified.length) {
    lines.push(
      `> **${stats.unverified.length} ${
        stats.unverified.length === 1 ? 'detail' : 'details'
      } below ${stats.unverified.length === 1 ? 'is' : 'are'} AI-generated and unverified.**`,
      '>',
      ...stats.unverified.map((t) => `> - ${t.text}`),
      '',
    );
  }

  if (stats.unverified.length) lines.push(`_${MARK_LEGEND}_`, '');

  for (const question of project.questions) {
    if (question.generatedAt === null) continue;
    lines.push(`## ${question.text}`, '');
    lines.push(`_${roleLabel(project, question)}${question.competency ? ` · ${question.competency}` : ''}_`, '');
    lines.push(segmentsToExportText(question.shortAnswer), '');
    if (question.coachingNote.trim()) {
      lines.push(`**Coaching note.** ${question.coachingNote}`, '');
    }
    if (question.longAnswer.length) {
      lines.push('### The material underneath', '', segmentsToExportText(question.longAnswer), '');
    }
  }

  const edits = corrections(project);
  if (edits.length) {
    lines.push('---', '', '## Corrections', '');
    for (const c of edits) {
      lines.push(`- **${c.current}** — Recall first wrote “${c.original}”`);
      if (c.note) lines.push(`  - ${c.note}`);
      lines.push(`  - ${c.questionText}`);
    }
    lines.push('');
  }

  lines.push('---', '', `_${verificationFooter(project)}_`, '');

  return lines.join('\n');
}

export function download(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'recall'
  );
}
